### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by yaoliUoA** [KASSII/benetech_1st_place_train#1]
Hi 

I have prepared the data as the readme. However, when I try to run "python3 AllChartTrain_v1/train.py", it failed to the error "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn"

| Name  | Type                               | Params
-------------------------------------------------------------
0 | model | Pix2StructForConditionalGeneration | 282 M 
-------------------------------------------------------------
282 M     Trainable params
0         Non-trainable params
282 M     Total params
2,259.600 Total estimated model params size (MB)
/home/local/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 20 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/local/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 20 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|                                                                                             | 0/59303 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/local/Project/chart/benetech_1st_place_train/deplot_train/AllChartTrain_v1/train.py", line 520, in <module>
    trainer.fit(model_module, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)

    model.backward(tensor, optimizer, optimizer_idx, *args, **kwargs)
  File "/home/local/.local/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1486, in backward
    loss.backward(*args, **kwargs)
  File "/home/local/.local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/local/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by KASSII** [comment]
Perhaps it is a different version of transformers. I tried to run it with the latest version and the error was reproduced in my environment.
I have also published requirements.txt as well, so please refer to that and reinstall the correct version.

**Comment by chenquan2002** [comment]
Can I get the script for data processing?
